- repo: git://github.com/dnephin/pre-commit-golang
  sha: HEAD
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-lint
    - id: validate-toml
    - id: g
    - id: gometalinter
    - id: golangci-lint
    - id: go-critic